# Generated by Django 3.0.5 on 2020-11-01 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(max_length=5)),
                ('house_no', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='District_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_state_id', models.CharField(max_length=5)),
                ('district', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marqueeHeading', models.CharField(default='', max_length=50)),
                ('heading', models.CharField(max_length=100)),
                ('pdf', models.FileField(default='', upload_to='pdf')),
                ('datePublished', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=5)),
                ('standard', models.IntegerField(choices=[(5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th')], default=5)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('teacher_id', models.CharField(max_length=5)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=5)),
                ('subject_id', models.CharField(max_length=5)),
                ('standard', models.IntegerField(choices=[(5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th')], default=5)),
                ('divison', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tenth_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, '2020-21'), (2022, '2021-22'), (2023, '2022-23'), (2024, '2023-24'), (2025, '2024-25'), (2026, '2025-26'), (2027, '2026-27')], default=2020, unique=True)),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearname', models.IntegerField(default=2020)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.School')),
            ],
        ),
        migrations.CreateModel(
            name='Tenth_Topper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('percentage', models.SmallIntegerField(default=100)),
                ('image', models.ImageField(default='', upload_to='media/images')),
                ('tenth_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Tenth_Result')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('studentname', models.CharField(default='', max_length=50)),
                ('standard', models.IntegerField(choices=[(5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th')], default=5)),
                ('divison', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(default=2020, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(blank=True, default=0)),
                ('subject_id', models.CharField(max_length=6)),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField()),
                ('father_name', models.CharField(max_length=40)),
                ('mother_name', models.CharField(max_length=40)),
                ('father_occupation', models.CharField(max_length=20)),
                ('mother_occupation', models.CharField(default='', max_length=20)),
                ('parent_contact_1', models.IntegerField(default=1234567890)),
                ('parent_contact_2', models.IntegerField(default=1234567890)),
                ('student_contact', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='media/images')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Address')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_no', models.IntegerField()),
                ('standard', models.IntegerField(choices=[(5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th')], default=5)),
                ('description', models.CharField(max_length=200)),
                ('divison', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=1)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('submission_date', models.DateField()),
                ('heading', models.CharField(max_length=50)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='City_district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_district_id', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=10)),
                ('district_state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.District_state')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city_district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.City_district'),
        ),
    ]
